export  default [
    {
      data: [
        {
          id: '1',
          title: 'Cline Family Cellers Famhouse Red',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic1.png'),
        },
        {
          id: '2',
          title: 'MacMurray Pinot Noir',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic2.png'),
        },
  
        {
          id: '3',
          title: 'Rutni Wines Trumpeter Malbec',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic3.png'),
        },
        {
          id: '4',
          title: 'Columbia Winery Merlot',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic4.png'),
        },
        {
          id: '5',
          title: 'Louis Martini Cabernet Sauvignon',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic5.png'),
        },
        {
          id: '6',
          title: 'Vinous Reverie Wine Merchant',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic6.png'),
        },
        {
          id: '7',
          title: 'Artesa Vineyards & Winery',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic1.png'),
        },
  
        {
          id: '8',
          title: 'Monticello Vineyards - Corley Family',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic2.png'),
        },
        {
          id: '9',
          title: 'Piazza Del Dotto Winery & Caves',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic3.png'),
        },
        {
          id: '10',
          title: 'M.S Torun Winery & Ranch',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic4.png'),
        },
        {
          id: '11',
          title: 'Vinous Reverie Wine Merchant',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic5.png'),
        },
        {
          id: '12',
          title: 'Artesa Vineyards & Winery',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic6.png'),
        },
  
        {
          id: '13',
          title: 'Monticello Vineyards - Corley Family',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic1.png'),
        },
        {
          id: '14',
          title: 'Piazza Del Dotto Winery & Caves',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic2.png'),
        },
        {
          id: '15',
          title: 'M.S Torun Winery & Ranch',
          decs: 'We will be tasting Rieslings from 5 different Alsatian Grand Crus! These wines come from privileged terroirs where geology, climate and exposure form an exceptional harmony. And the great Riesling grape is the ideal catalyst to showcase how each individual site differs. Great opportunity to experience Alsace! ',
          date: 'FEB 3',
          time: 'Closes 6:00 PM PST',
          lacation: 'Vinious Reverie Winery Walnut Creeks, CA',
          audience: '45 Attendees',
          image: require('../../../assets/images/WineBottles/WineBottlePic3.png'),
        },
      ],
    },
  ];