export default [
{
    id: '1',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic1.jpg'),
},{
    id: '2',
    marchant: 'Howell Mountain Vinters',
    title: 'Taste of Howell Mountain',
    date: 'FEB 12',
    time: '3:00PM - 6:00 PM PST',
    location: 'Charles Krug Winery Saint Helena, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic2.jpg'),
},{
    id: '3',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic3.jpg'),
},{
    id: '4',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic4.jpg'),
},
{
    id: '5',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic1.jpg'),
},{
    id: '6',
    marchant: 'Howell Mountain Vinters',
    title: 'Taste of Howell Mountain',
    date: 'FEB 12',
    time: '3:00PM - 6:00 PM PST',
    location: 'Charles Krug Winery Saint Helena, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic2.jpg'),
},{
    id: '7',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic3.jpg'),
},{
    id: '8',
    marchant: 'Vinous Reverie Wine Merchant',
    title: 'Alsace Grand Cru Riesling Tasting',
    date: 'FEB 3',
    time: '5:00PM - 7:00 PM PST',
    location: 'Vinoud Reverie Winery Walnut Creek, CA',
    image: require('../../../../assets/images/HomeCrousel/Pic4.jpg'),
},
]